language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
env:
  - EXTRA=1
  - GEVENT_FILE=thread
matrix:
 allow_failures:
   - env: GEVENT_BACKEND=signalfd
   - python: 2.5
     env: DEBUGPY=-dbg GEVENTSETUP_EV_VERIFY=3
 include:
   - python: 2.7
     env: DEBUGPY=-dbg GEVENTSETUP_EV_VERIFY=3
   - python: 2.7
     env: DEBUGPY=-dbg GEVENTSETUP_EV_VERIFY=3 GEVENT_FILE=thread
   - python: 2.7
     env: GEVENT_BACKEND=select GEVENTSETUP_EV_VERIFY=3
   - python: 2.7
     env: GEVENT_BACKEND=poll GEVENTSETUP_EV_VERIFY=3
   - python: 2.7
     env: GEVENT_BACKEND=nosigmask,noinotify GEVENTSETUP_EV_VERIFY=3
   - python: 2.6
     env: DEBUGPY=-dbg GEVENTSETUP_EV_VERIFY=3
   - python: 2.7
     env: GEVENT_BACKEND=signalfd
   - python: 2.5
     env: DEBUGPY=-dbg GEVENTSETUP_EV_VERIFY=3
install:
 - pip install --use-mirrors cython
 - cython --version
 - pip install --use-mirrors greenlet psycopg2 pysendfile web.py
 - if [ "x$TRAVIS_PYTHON_VERSION" == "x2.5" ]; then sudo apt-get install libssl-dev libkrb5-dev libbluetooth-dev; pip install --use-mirrors sslfix; fi
 - if [ "x$TRAVIS_PYTHON_VERSION" == "x2.7" ]; then pip install --use-mirrors -q pep8; fi
 - python -c 'import greenlet; print greenlet, greenlet.__version__; import psycopg2; print psycopg2, psycopg2.__version__; import web; print web, web.__version__'
 - export CYTHON=`which cython`
 - python setup.py install
script:
 - cd greentest && python testrunner.py --full --expected ../known_failures.txt
notifications:
  email:
    recipients:
      - denis.bilenko@gmail.com
    on_success: change
    on_failure: change
